import json, os
R=lambda n: os.path.abspath(os.path.join('refs',n))
REFS=[R('kop-A.png'),R('kop-B.png'),R('duo-pose.jpg'),R('polo-borstprint.png'),R('logo-topmovers.png')]
WIE=("Two real men, reproduced exactly from the attached references, standing shoulder to shoulder in a warehouse pose but on a flat magenta void, both laughing heartily and looking into the lens. "
 "Man A (face reference 1, stands on the LEFT): about 60 years old, medium build, grey wavy medium-length hair, round thin-rimmed glasses, clean-shaven, laughing with an open mouth; he wears a dark navy long-sleeved shirt with a bright orange high-visibility safety vest over it with two horizontal silver reflective stripes at the bottom; his right arm goes behind man B's back. "
 "Man B (face reference 2, stands on the RIGHT): about 58 years old, lean, very short grey hair, thin rectangular glasses, short grey goatee and stubble, broad laugh; he wears a mid-grey Top Movers polo shirt with three buttons and short sleeves, the small Top Movers chest print on the left chest; his left arm rests around man A's shoulders, his right arm hangs relaxed at his side. "
 "Every face exactly like its reference: same age (no younger, no older), same weight (not heavier), same hairline, same glasses. Pose and clothing exactly as in the attached photo (reference 3).")
MERK=("The chest print on the grey polo is the Top Movers logo exactly as in the attached polo reference (4) and the logo file (5, the LAST attached image): TOP in bold white capitals, MOVERS in white italic capitals directly beneath, a thin teal (#00A19B) swoosh curving from lower left to an arrow point at the right; about 8 cm wide, left chest, exactly once, never mirrored, letters left to right. No text on the vest, no badge, no other logo anywhere.")
CUT=("ABSOLUTE RULE, cutout plate: the background is one flat, even, pure magenta (#FF00FF) void that fills the frame edge to edge; nothing is rendered behind the men: no warehouse, no shelves, no pallets, no wall, no floor, no ground line, no shadow on the background, no backdrop, no lighter panel, no vignette. "
 "The flat magenta is visible in every gap: between the arms and the torsos, under the elbows, and above and beside the two heads. "
 "The bottom edge of the frame cuts through the upper thighs, just below the bottom of the vest and the hands, so both hands are completely in the frame; no knees, no feet. "
 "The two men fill about 66 percent of the frame width, centred, with clear empty magenta on the left, right and above the heads; no body part touches or comes near the left, right or top border. No outline, no glow and no white edge around the men: skin, hair and cloth meet the magenta directly with natural soft edges.")
CAM=("Camera and light: 85 mm lens from 3.5 meters at chest height, f/5.6, both faces and the chest print sharp. Bright, even, slightly cool warehouse daylight from above and the front, soft-edged shadows, skin with real pores and fine lines, slight sensor noise, natural colours, the orange vest saturated but not clipped, no HDR, no plastic skin, no teal-orange grading. Real photograph, not an illustration or 3D render.")
NEG=("Negative: no extra people, no third person, no misspelled or mirrored letters, no extra words, no badges, no lanyard, no props, no pallets, no shelves, no floor, no wall, no shadow on the background, no white outline, no glow, no illustration, no extra fingers, no caps, no knees, no feet, no shoes.")
def job(n, extra): return {'name':n,'prompt':"\n".join([WIE,MERK,CUT,CAM+" "+extra,"Attached images in order: 1) face reference man A; 2) face reference man B; 3) the photo with the exact pose and clothing; 4) brand reference: the chest print on a polo; 5) the LAST attached image is the exact Top Movers logo file.",NEG]),'refs':REFS,'aspect':'4:3','size':'2K'}
JOBS=[job('duo61-01',''),job('duo61-02','Both laugh a little less wide, warm smiles with teeth showing.'),job('duo61-03','Man B holds his right hand at his hip with the thumb hooked in the pocket, elbow out so the magenta shows between arm and torso.'),job('duo61-04','Both stand a touch more upright and face the camera squarely.')]
json.dump(JOBS,open('jobs-61.json','w'),indent=1); print(len(JOBS),'jobs')
