"""Jobs: de drie Top Movers-medewerkers van foto 67 (duim omhoog) opnieuw als cutout-plaat op magenta, met hun eigen
gezichten, kleding en houding als referentie, zodat de uitsnede per chroma-key schoon wordt (Vision liet de achtergrond
tussen de armen staan). Gebruik: python3 bouw_jobs_67.py -> jobs-67.json"""
import json, os
R=lambda n: os.path.abspath(os.path.join('refs',n))
REFS=[R('kop-A.png'),R('kop-B.png'),R('kop-C.png'),R('trio-pose.jpg'),R('polo-borstprint.png'),R('logo-topmovers.png')]
WIE=("Three real Top Movers employees, reproduced exactly from the attached references, standing shoulder to shoulder, all three giving a thumbs-up with the right hand at chest height and looking into the lens with a genuine, relaxed smile (not identical grins). "
 "Man A (face reference 1, stands on the LEFT): about 30 years old, medium build, short light-brown hair with a fade, short light-brown beard, no glasses; he wears a mid-grey polo-collar sweatshirt with three buttons and long sleeves, the small Top Movers chest print on the left chest; his left hand rests loosely at his left hip. "
 "Man B (face reference 2, stands in the MIDDLE, half a step back): about 40 years old, slim, short brown hair, black rectangular glasses, light stubble; he wears a dark anthracite crew-neck t-shirt with the small Top Movers chest print; his left hand rests on his left hip, elbow out. "
 "Man C (face reference 3, stands on the RIGHT): about 55 years old, sturdy build, short thinning grey hair, round thin-rimmed glasses, grey stubble; he wears a black polo shirt with the small Top Movers chest print and a black wristwatch on his left wrist; his left hand rests at his left hip. "
 "Every face exactly like its reference: same age (no younger, no older), same weight (not heavier), same hairline, same glasses. Poses and clothing exactly as in the attached group photo (reference 4).")
MERK=("The chest print on every shirt is the Top Movers logo exactly as in the attached polo reference (5) and the logo file (6, the LAST attached image): TOP in bold white capitals, MOVERS in white italic capitals directly beneath, a thin teal (#00A19B) swoosh curving from lower left to an arrow point at the right; about 8 cm wide, on the left chest, exactly once per shirt, never mirrored, letters left to right. No other text, badge, lanyard or logo anywhere.")
CUT=("ABSOLUTE RULE, cutout plate: the background is one flat, even, pure magenta (#FF00FF) void that fills the frame edge to edge; nothing is rendered behind the men: no room, no wall, no window, no floor, no ground line, no horizon, no shadow on the background, no backdrop, no lighter panel, no vignette. "
 "The flat magenta is visible in EVERY gap: between each arm and the torso, between the elbows and the neighbouring man, between the three men's shoulders and heads, and around the thumbs. The men do not overlap each other except a slight shoulder overlap. "
 "The bottom edge of the frame cuts through the upper thighs just below the hands at the hips, so both hands of every man are completely in the frame; no knees, no feet. "
 "The group fills about 62 percent of the frame width, centred, with clear empty magenta on the left, right and above the heads; no body part touches or comes near the left, right or top border. No outline, no glow and no white edge around the men: skin, hair and cloth meet the magenta directly with natural soft edges.")
CAM=("Camera and light: 85 mm lens from 4 meters at chest height, f/5.6, all three faces and chest prints sharp. Soft, bright, slightly cool office daylight from the front-left, gentle soft-edged shadows, mixed with warm ceiling light; skin with real pores and fine lines, slight sensor noise, natural colours, no HDR, no plastic skin, no teal-orange grading. Real photograph, not an illustration or 3D render.")
NEG=("Negative: no extra people, no fourth person, no misspelled or mirrored letters, no extra words on the shirts, no badges, no lanyard, no boxes, no props, no floor, no wall, no window, no shadow on the background, no white outline, no glow, no illustration, no extra fingers, no caps, no knees, no feet, no shoes.")
def job(n, extra):
    return {'name':n,'prompt':"\n".join([WIE,MERK,CUT,CAM+" "+extra,"Attached images in order: 1) face reference man A; 2) face reference man B; 3) face reference man C; 4) the group photo with the exact poses and clothing; 5) brand reference: the chest print on a dark polo; 6) the LAST attached image is the exact Top Movers logo file.",NEG]),'refs':REFS,'aspect':'16:9','size':'2K'}
JOBS=[job('trio67-01',''),job('trio67-02','Slightly more space between the three men so the magenta gaps are wide.'),job('trio67-03','Man B stands level with the other two instead of behind them.'),job('trio67-04','All three hold the thumbs-up a little higher, at shoulder height, elbows slightly away from the body so the magenta shows between arm and torso.')]
json.dump(JOBS,open('jobs-67.json','w'),indent=1); print(len(JOBS),'jobs')
